language: python
python:
  - "2.7"
before_install:
  - sudo apt-get -y install jq
  - wget `curl https://api.github.com/repos/jgm/pandoc/releases/latest | jq -r '.assets[] | .browser_download_url | select(endswith("deb"))'` -O pandoc.deb
  - sudo dpkg -i pandoc.deb
  - git clone --recursive https://github.com/getpelican/pelican-plugins
  - rm -rf pelican-plugins/pandoc_reader
  - git clone https://github.com/kdheepak89/pandoc_reader.git pelican-plugins/pandoc_reader
  - git clone https://github.com/kdheepak89/pelican-smoothie.git pelican-themes/pelican-smoothie
install:
  - easy_install -U setuptools
  - pip install -U pip wheel
  - pip install -r requirements.txt
before_script:
  - git config user.name "Travis-CI"
  - git config user.email "noreply@travis-ci.org"
  - COMMIT_MESSAGE="Publishing site on `date "+%Y-%m-%d %H:%M:%S"` from `git log -n 1 --format='commit %h - %s'`"
  - export PATH=$PATH:/home/travis/.cabal/bin
script:
  - echo "Running script"
  - make publish
after_success:
  - make travis-github
  - git push -f -q https://kdheepak89:$(GITHUB_API_KEY)@github.com/kdheepak89/blog gh-pages &2>/dev/null
notifications:
  email: false
# whitelist
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.cache/pip

