project:
  type: website
  post-render:
    - julia ./_quarto/post-render.jl

author: "Dheepak Krishnamurthy"

website:
  title: "Î”"
  favicon: ./_quarto/favicon.svg
  search:
    location: navbar
  site-url: https://blog.kdheepak.com
  repo-url: https://github.com/kdheepak/blog
  repo-actions: [edit, issue]
  open-graph: true
  sidebar:
    alignment: left
    style: docked
  navbar:
    search: true
    pinned: false
    right:
      - icon: github
        href: https://github.com/kdheepak
        aria-label: GitHub
format:
  html:
    grid:
      content-mode: full
    theme:
      - pulse
      - ./_quarto/theme.scss
    css:
      - ./_quarto/styles.css
    code-copy: hover
    code-tools:
      source: repo
    highlight-style: github
    anchor-sections: true
    section-divs: true
    email-obfuscation: javascript
    html-q-tags: true
    toc: true
    toc-location: left
    toc-depth: 3
    shift-heading-level-by: 1
    number-sections: false
    callout-appearance: simple
    title-block-banner: true
    title-block-categories: false
    citations-hover: true
    cap-location: margin
    citation: true
    from: markdown+emoji+mark
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/blog\.kdheepak\.com\/'
    filters:
      - _quarto/alert.lua
    comments:
      hypothesis: true
      giscus:
        repo: kdheepak/blog
        category: Comments
        reactions-enabled: true
        loading: lazy
        input-position: top
        mapping: url

quarto-required: ">= 1.3.0"
links-as-notes: true
link-citations: true
crossref:
  fig-prefix: Figure
  tbl-prefix: Table
  eq-prefix: Equation

execute:
  cache: true
  output: true
  echo: true
  warning: true
  error: true
  freeze: auto
  eval: true
  daemon: true

jupyter: julia-1.8

bibliography: ./_quarto/blog.bib
csl: ./_quarto/ieee.csl
license: CC BY-SA
