name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.local/share/virtualenvs
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo install svgbob_cli
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Install pipenv
        run: pipx install pipenv
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - run: pipenv install
      - uses: actions/setup-node@v2
      - name: Build
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.17.1.1/pandoc-2.17.1.1-1-amd64.deb -O /tmp/pandoc.deb
          sudo dpkg -i /tmp/pandoc.deb
          pandoc --version
          node --version
          svgbob_cli --version
          python --version
          npm install
          NODE_ENV=production pipenv run npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
