name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run apt update and install
        run: |
          sudo apt-get update
          sudo apt install texlive-latex-extra texlive-base texlive-fonts-extra pdf2svg imagemagick ghostscript
      - name: Download Pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.17.1.1/pandoc-2.17.1.1-1-amd64.deb -O /tmp/pandoc.deb
          sudo dpkg -i /tmp/pandoc.deb
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache cargo installs
        uses: actions/cache@v3
        id: cache-cargo
        with:
          path: |
            ~/.cargo/
          key: ${{ runner.os }}-cargo
      - name: Cargo install
        run: |
          cargo install svgbob_cli --force
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        if: steps.cache-cargo.outputs.cache-hit != 'true'
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Check
        run: |
          pandoc --version
          node --version
          svgbob_cli --version
          python --version
      - name: Cache npm
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: NPM install
        run: |
          npm install
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install pdm
        run: |
          pip install pipx
          pipx install pdm
      - name: PDM install
        run: |
          pdm install
      - name: Build
        run: |
          pdm run npm run build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
          NODE_ENV: "production"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build
          single-commit: true
