name: Docker
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Registry
      uses: docker/build-push-action@v2
      with:
        cache_froms: kdheepak/blog:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        always_pull: true
        dockerfile: Dockerfile
        tags: latest
        push: ${{ github.ref == 'refs/heads/master' }}
